# Generated by Django 5.0.2 on 2024-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter a language (e.g. English, Spanish etc.)', max_length=40, unique=True),
        ),
    ]
